- name: install and run nginx
  become: yes
  hosts: web
  tasks:
   - name: install nginx
     ansible.builtin.dnf:
      name: nginx
      state: latest
   - name: nginx
     ansible.buitlin.service:
      name: start nginx
      state: started
      enabled: yes

    