- name: install and run nginx
  become: yes
  hosts: web
  tasks:
   - name: install nginx
     ansible.builtin.dnf:
      name: nginx
      state: absent
   - name: start nginx
     ansible.builtin.service:
      name: nginx
      state: stopped
      enabled: no

    