- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"

- name: uppercase
  hosts: localhost
  tasks:
  - name: convert into upper case
    vars:
      greeting: "Hello, good morning"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: lowercase
  hosts: localhost
  vars:
    greeting: "HELLO, GOOD EVENING"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"
- name: remove duplicate
  hosts: localhost
  vars:
    numbers: [1, 2, 2, 3, 4, 4, 5, 5]
  tasks:
  - name: remove duplicate numbers
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: print min and max
  hosts: localhost
  vars:
    list: [50, 99, 107, 221, 39, 47]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: "minimum value is: {{ list | min }} & maximum value is: {{ list | max }}"

- name: convert dictionary into list/items
  hosts: localhost
  vars:
    dictionary:
      name: chandu
      age: 500
      work: hand job
      alive: yes
  tasks:
  - name: convert into list
    ansible.builtin.debug:
      msg: "{{ dictionary | dict2items }}"

- name: convert items to dictionary
  hosts: localhost
  vars:
    list:
     [
        {
            "key": "name",
            "value": "chandu"
        },
        {
            "key": "age",
            "value": 500
        },
        {
            "key": "work",
            "value": "hand job"
        },
        {
            "key": "alive",
            "value": true
        }
    ]
  tasks:
  - name: convert to dict2items
    ansible.builtin.debug:
      msg: "{{ list | items2dict }}"
