- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"

- name: uppercase
  hosts: localhost
  tasks:
  - name: convert into upper case
    vars:
      greeting: "Hello, good morning"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: lowercase
  hosts: localhost
  vars:
    greeting: "HELLO, GOOD EVENING"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"
- name: remove duplicate
  hosts: localhost
  numbers: [1, 2, 2, 3, 4, 4, 5, 5]
  tasks:
  - name: remove duplicate numbers
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"